import sqlite3

conn = sqlite3.connect("darbuotojai2.db")
c = conn.cursor()

with conn:
    c.execute("""SELECT * From DARBUOTOJAS WHERE ASMENS_KODAS='38807200000'""")
    # c.execute("""SELECT * FROM DARBUOTOJAS WHERE DIRBA_NUO '2009-10-30' AND '2012-11-11'""")
    c.execute("""SELECT VARDAS, SKYRIUS_ID, PROJEKTAS_ID FROM DARBUOTOJAS WHERE SKYRIUS_ID IN (2, 3)""")
    c.execute(
        """SELECT VARDAS, PAVARDĖ, ASMENS_KODAS FROM DARBUOTOJAS WHERE ASMENS_KODAS LIKE '4%' OR ASMENS_KODAS LIKE '6%'""")
    c.execute("""SELECT * FROM DARBUOTOJAS WHERE ASMENS_KODAS LIKE '_____12%'""")
    c.execute("""SELECT * FROM PROJEKTAS WHERE PAVADINIMAS LIKE '_a%'""")
    c.execute("""SELECT * FROM DARBUOTOJAS WHERE PAREIGOS ISNULL""")
    c.execute(
        """SELECT VARDAS, PAVARDĖ, DIRBA_NUO, PAREIGOS FROM DARBUOTOJAS WHERE DIRBA_NUO >= '2011-02-12' AND PAREIGOS = 'Programuotojas'""")
    c.execute(
        """SELECT VARDAS, PAVARDĖ, SKYRIUS_ID, PROJEKTAS_ID FROM DARBUOTOJAS WHERE SKYRIUS_ID = 2 OR PROJEKTAS_ID = 1""")
    c.execute("""SELECT VARDAS FROM DARBUOTOJAS WHERE VARDAS NOT LIKE 'A%'""")
    c.execute("""SELECT VARDAS, PAVARDĖ, DIRBA_NUO FROM DARBUOTOJAS ORDER BY DIRBA_NUO ASC""")
    c.execute("""SELECT VARDAS, PAVARDĖ, DIRBA_NUO FROM DARBUOTOJAS ORDER BY DIRBA_NUO DESC""")
    c.execute("""SELECT max(PROJEKTAS_ID), min(PROJEKTAS_ID) FROM DARBUOTOJAS""")
    c.execute("""SELECT PROJEKTAS_ID, count(*) FROM DARBUOTOJAS GROUP BY PROJEKTAS_ID ORDER BY count(*) DESC""")
    c.execute("""SELECT PROJEKTAS_ID, count(*) FROM DARBUOTOJAS GROUP BY PROJEKTAS_ID HAVING count(*) >3""")
    c.execute(
        """SELECT PROJEKTAS_ID, PAREIGOS, count(*) FROM DARBUOTOJAS WHERE PAREIGOS = "Programuotojas" GROUP BY PROJEKTAS_ID ORDER BY count(*) DESC""")
    print(c.fetchall())

conn.commit()
conn.close()
