import sqlite3

conn = sqlite3.connect("darbuotojai3.db")
c = conn.cursor()

with conn:
    # c.execute("""SELECT DARBUOTOJAS.VARDAS, DARBUOTOJAS.PAVARDĖ, PROJEKTAS.PAVADINIMAS
    # FROM DARBUOTOJAS, PROJEKTAS
    # WHERE DARBUOTOJAS.VARDAS = VARDAS""")
    # c.execute("""SELECT DARBUOTOJAS.VARDAS, DARBUOTOJAS.PAVARDĖ, PROJEKTAS.PAVADINIMAS
    # FROM DARBUOTOJAS, PROJEKTAS
    # WHERE PROJEKTAS.PAVADINIMAS = "Galerija" """)
    # c.execute("""SELECT DARBUOTOJAS.VARDAS, DARBUOTOJAS.PAVARDĖ, PROJEKTAS.PAVADINIMAS, SKYRIUS.PAVADINIMAS
    # FROM DARBUOTOJAS
    # JOIN PROJEKTAS ON DARBUOTOJAS.PROJEKTAS_ID = PROJEKTAS.ID
    # JOIN SKYRIUS ON DARBUOTOJAS.SKYRIUS_ID = SKYRIUS.ID
    # WHERE SKYRIUS.PAVADINIMAS = "Pardavimų" """)
    # c.execute("""SELECT DARBUOTOJAS.VARDAS, DARBUOTOJAS.PAVARDĖ, PROJEKTAS.PAVADINIMAS
    # FROM DARBUOTOJAS
    # JOIN PROJEKTAS ON DARBUOTOJAS.PROJEKTAS_ID = PROJEKTAS.ID
    # WHERE PROJEKTAS.PAVADINIMAS = "Projektų valdymas"
    # AND DARBUOTOJAS.ASMENS_KODAS LIKE '4%' OR DARBUOTOJAS.ASMENS_KODAS LIKE '6%' """)
    # c.execute("""SELECT SKYRIUS.PAVADINIMAS, count(*) as count
    # FROM DARBUOTOJAS
    # JOIN SKYRIUS ON DARBUOTOJAS.SKYRIUS_ID = SKYRIUS.ID
    # GROUP BY SKYRIUS.ID""")
    # c.execute("""SELECT SKYRIUS.PAVADINIMAS, count(*) as count
    # FROM DARBUOTOJAS
    # JOIN SKYRIUS ON DARBUOTOJAS.SKYRIUS_ID = SKYRIUS.ID
    # GROUP BY SKYRIUS.ID
    # HAVING count() >= 5""")
    # c.execute("""INSERT INTO DARBUOTOJAS (VARDAS, PAVARDĖ, ASMENS_KODAS, DIRBA_NUO) VALUES
    # ("Pranas", "Logis", "38807117896", "2009-11-12") """)
    # c.execute("""SELECT DARBUOTOJAS.VARDAS, DARBUOTOJAS.PAVARDĖ, SKYRIUS.PAVADINIMAS
    # LEFT JOIN SKYRIUS ON DARBUOTOJAS.SKYRIUS_ID = SKYRIUS.ID""")
    c.execute("""SELECT DARBUOTOJAS.VARDAS, DARBUOTOJAS.PAVARDĖ, PROJEKTAS.PAVADINIMAS
         FROM DARBUOTOJAS
         JOIN PROJEKTAS ON DARBUOTOJAS.PROJEKTAS_ID = PROJEKTAS.ID
         WHERE DARBUOTOJAS.PROJEKTAS_ID IN (
            SELECT DARBUOTOJAS.PROJEKTAS_ID
            FROM DARBUOTOJAS
            GROUP BY DARBUOTOJAS.PROJEKTAS_ID
            HAVING count() > 4) """)
    print(c.fetchall())

conn.commit()
conn.close()
